owner: smart-oversight
repo: smartoversight-status

sites:
  - name: Smart Oversight Website
    url: https://www.smart-oversight.com/
  - name: So Comply Luxembourg
    url: https://app-lux.so-comply.com/
  - name: So Comply Luxembourg Api
    url: https://api-lux.so-comply.com/v1/health-check
  - name: So Comply Europe
    url: https://app.so-comply.com/
  - name: So Comply Europe Api
    url: https://api.so-comply.com/v1/health-check
  - name: So Comply Switzerland
    url: https://app-swiss.so-comply.com/
  - name: So Comply Switzerland Api
    url: https://api-swiss.so-comply.com/v1/health-check

status-website:
  baseUrl: /smartoversight-status
  logoUrl: https://www.smart-oversight.com/wp-content/uploads/Logo-smartoversight.png
  name: Smart Oversight Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/smart-oversight/smartoversight-status
